[0m12:39:34.404428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021096CFE1D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021096CD5F90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210968B3290>]}


============================== 12:39:34.420076 | e404f4b7-48e7-460a-9113-dfc250ceaf92 ==============================
[0m12:39:34.420076 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:39:34.420076 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt init jaffle_shop', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:39:34.461364 [debug] [MainThread]: Starter project path: c:\Users\damia\dbt\analytics_engineer_exercise\.venv\Lib\site-packages\dbt\include\starter_project
[0m12:39:34.477919 [info ] [MainThread]: 
Your new dbt project "jaffle_shop" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m12:39:34.477919 [info ] [MainThread]: Setting up your profile.
[0m12:40:44.283523 [info ] [MainThread]: Profile jaffle_shop written to C:\Users\damia\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m12:40:44.283523 [debug] [MainThread]: Command `dbt init` succeeded at 12:40:44.283523 after 69.96 seconds
[0m12:40:44.283523 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000210918129D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021096C93C90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021096C93F10>]}
[0m12:40:44.283523 [debug] [MainThread]: Flushing usage events
[0m12:40:44.601959 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:53:45.754995 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E388F88D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E388FBFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E388F8B10>]}


============================== 12:53:45.770014 | 00db6ad0-8a68-49dd-856a-5db9219ba9a6 ==============================
[0m12:53:45.770014 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:53:45.770014 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'invocation_command': 'dbt run', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:53:45.770014 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:53:45.770014 [debug] [MainThread]: Command `dbt run` failed at 12:53:45.770014 after 0.10 seconds
[0m12:53:45.770014 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E33412790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E334127D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018E388F8110>]}
[0m12:53:45.770014 [debug] [MainThread]: Flushing usage events
[0m12:53:46.097188 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:55:22.202844 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D2480B6BD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D2484F8390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D2484FBFD0>]}


============================== 12:55:22.218469 | b18ce8c1-4533-420a-86a5-49b6210ec347 ==============================
[0m12:55:22.218469 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:55:22.218469 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m12:55:22.218469 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:55:22.218469 [debug] [MainThread]: Command `dbt run` failed at 12:55:22.218469 after 0.10 seconds
[0m12:55:22.218469 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D24849E3D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D243011B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002D2484FAC50>]}
[0m12:55:22.218469 [debug] [MainThread]: Flushing usage events
[0m12:55:22.580324 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:56:10.833370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191627F35D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191627FBA50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191627FAB50>]}


============================== 12:56:10.833370 | 041429e1-96a6-4406-bbef-a115e95590c2 ==============================
[0m12:56:10.833370 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:56:10.833370 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:56:10.833370 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:56:10.833370 [debug] [MainThread]: Command `dbt run` failed at 12:56:10.833370 after 0.11 seconds
[0m12:56:10.833370 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191627F3E10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001915D261B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000191627FBAD0>]}
[0m12:56:10.833370 [debug] [MainThread]: Flushing usage events
[0m12:56:11.165609 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:56:30.837508 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269742FBD90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002697429CF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269742FBDD0>]}


============================== 12:56:30.837508 | 160f65ae-daa5-49b9-8c28-b0e12b2344d9 ==============================
[0m12:56:30.837508 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:56:30.853133 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m12:56:30.853133 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:56:30.853133 [debug] [MainThread]: Command `dbt run` failed at 12:56:30.853133 after 0.11 seconds
[0m12:56:30.853133 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002696EE11B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000269742FAC50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026972DAF6D0>]}
[0m12:56:30.853133 [debug] [MainThread]: Flushing usage events
[0m12:56:31.181607 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:58:01.145065 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FC44FBE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FC449D050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FC44FA6D0>]}


============================== 12:58:01.147591 | 7d8425ed-8203-44c5-bda3-7ab3d2dfe0c9 ==============================
[0m12:58:01.147591 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:58:01.147591 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:58:01.147591 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:58:01.147591 [debug] [MainThread]: Command `dbt run` failed at 12:58:01.147591 after 0.12 seconds
[0m12:58:01.158679 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FC449E790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FC40B3010>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000013FBEE62910>]}
[0m12:58:01.160637 [debug] [MainThread]: Flushing usage events
[0m12:58:01.511003 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m12:58:08.664971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D29DF90D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D29D9CF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D29AA2F90>]}


============================== 12:58:08.664971 | a2d204bc-328f-41b5-a9a8-794e9e28d3a4 ==============================
[0m12:58:08.664971 [info ] [MainThread]: Running with dbt=1.9.1
[0m12:58:08.664971 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m12:58:08.664971 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m12:58:08.664971 [debug] [MainThread]: Command `dbt run` failed at 12:58:08.664971 after 0.09 seconds
[0m12:58:08.664971 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D24861B90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D29DFBC90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D29DFAC50>]}
[0m12:58:08.680629 [debug] [MainThread]: Flushing usage events
[0m12:58:08.993651 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m15:32:34.747610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445E119D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445BF88D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445BFA6D0>]}


============================== 15:32:34.747610 | a7f77b2d-3d48-403e-9870-4cd5ad2bd334 ==============================
[0m15:32:34.747610 [info ] [MainThread]: Running with dbt=1.9.1
[0m15:32:34.747610 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\damia\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run -f -s +final_leads', 'send_anonymous_usage_stats': 'True'}
[0m15:32:34.747610 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\damia\dbt\analytics_engineer_exercise\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:32:34.747610 [debug] [MainThread]: Command `dbt run` failed at 15:32:34.747610 after 0.09 seconds
[0m15:32:34.747610 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445B9D790>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445B93F10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000024445B93FD0>]}
[0m15:32:34.747610 [debug] [MainThread]: Flushing usage events
[0m15:32:35.124170 [debug] [MainThread]: An error was encountered while trying to flush usage events
